/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Content.glb --transform --shadows --keepmaterials --keepmeshes --keepnames 
Files: Content.glb [41.37MB] > C:\Users\abhishek\Desktop\dri proj\DRI-Gamified-Final\public\Content-transformed.glb [6.67MB] (84%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Content(props) {
  const { nodes, materials } = useGLTF("/Content-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials["Material.010"]}
        position={[-63.111, -0.224, 55.999]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[49.2, 50.209, 56.114]}
      />
      <group position={[-112.386, -3.115, 13.871]} scale={0.164}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube146.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube146_1.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Apartment1_BaseMaterial_0001.geometry}
        material={materials.BaseMaterial}
        position={[-25.116, 2.04, 35.569]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <group
        position={[-14.759, 3.971, 28.564]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.506}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building11002.geometry}
          material={materials["Black.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building11002_1.geometry}
          material={materials["Windows.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building11002_2.geometry}
          material={materials["Cover2.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building11002_3.geometry}
          material={materials["Door1.001"]}
        />
      </group>
      <group
        position={[-13.241, 4.045, 35.365]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.506}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3002.geometry}
          material={materials["WhiteBuild.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building3002_1.geometry}
          material={materials["Cover1.004"]}
        />
      </group>
      <group
        position={[-21.158, 5.59, 36.254]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.506}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building5011.geometry}
          material={materials["Antena.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building5011_1.geometry}
          material={materials["Edges.001"]}
        />
      </group>
      <group
        position={[-17.46, 4.386, 33.112]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.506}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building6002.geometry}
          material={materials["LightYellow.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building6002_1.geometry}
          material={materials["Building6Top.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building6002_2.geometry}
          material={materials["Door2.001"]}
        />
      </group>
      <group
        position={[-19.404, 3.033, 27.767]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.506}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building8002.geometry}
          material={materials["Build6.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Building8002_1.geometry}
          material={materials["LightBrownDoor.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube108.geometry}
        material={nodes.Cube108.material}
        position={[-111.009, -0.168, 39.614]}
        rotation={[Math.PI, Math.PI / 2, 0]}
        scale={[-4.478, 0.336, 6.409]}
      />
      <group
        position={[-37.367, 2.952, 14.373]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.506}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hospital002_1.geometry}
          material={materials["Cross.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hospital002_2.geometry}
          material={materials["Hospital2.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.House.geometry}
        material={materials["World ap"]}
        position={[-101.623, 1.371, 40.54]}
        rotation={[Math.PI, 0, 0]}
        scale={0.01}
      />
      <group
        position={[-103.984, 1.667, 36.164]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lowpoly_Tree_07_Material_0001.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Lowpoly_Tree_07_Material_0001_1.geometry}
          material={materials["Material.033"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube232.geometry}
        material={materials["Walls.001"]}
        position={[-114.417, 0.577, 12.655]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[3.763, 0.75, 0.216]}
      />
      <group
        position={[-96.982, 21.08, 28.418]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[2.564, 0.64, 2.564]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[-96.982, 21.08, 28.418]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[2.564, 0.64, 2.564]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022.geometry}
          material={materials.Plastic_Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_1.geometry}
          material={materials["02_-_Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_2.geometry}
          material={materials["09_-_Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_3.geometry}
          material={materials["lambert6.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_4.geometry}
          material={materials["14_-_Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_5.geometry}
          material={materials["13_-_Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_6.geometry}
          material={materials.lambert2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_7.geometry}
          material={materials["lambert10.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_8.geometry}
          material={materials.lambert11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_9.geometry}
          material={materials["lambert9.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_10.geometry}
          material={materials["lambert5.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_11.geometry}
          material={materials["lambert3.001"]}
        />
      </group>
      <group
        position={[-42.891, -1.113, 31.273]}
        rotation={[0, 0, Math.PI]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004.geometry}
          material={materials["Mtl_Concrete.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_1.geometry}
          material={materials["Mtl_RoofItems.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_2.geometry}
          material={materials["Mtl_Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_3.geometry}
          material={materials["Mtl_DifferentRow.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_4.geometry}
          material={materials["Mtl_Roof.001"]}
        />
      </group>
      <group
        position={[-107.339, 0.18, 23.665]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={0.002}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5009.geometry}
          material={materials.lambert44SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5009_1.geometry}
          material={materials.lambert25SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5009_2.geometry}
          material={materials.lambert35SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5009_3.geometry}
          material={materials.lambert38SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5009_4.geometry}
          material={materials.lambert42SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5009_5.geometry}
          material={materials.lambert48SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5009_6.geometry}
          material={materials.lambert51SG}
        />
      </group>
      <group
        position={[-73.427, 11.278, 27.654]}
        rotation={[-1.469, 0, 0]}
        scale={1.209}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_digital_display_sides_0_1.geometry}
          material={materials.digital_display_sides}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_digital_display_sides_0_2.geometry}
          material={materials.digital_displays}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_digital_display_sides_0_3.geometry}
          material={materials.metal_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_digital_display_sides_0_4.geometry}
          material={materials.metal_1}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Skyscraper3001.geometry}
        material={materials["BaseMaterial.001"]}
        position={[-80.007, 8.712, 13.62]}
        scale={1.537}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere008.geometry}
        material={materials.Map}
        position={[-99.845, 5.017, 26.406]}
        rotation={[-0.452, -0.734, 0.055]}
        scale={1.868}
      />
      <group
        position={[-55.921, -0.498, 17.622]}
        rotation={[0, 0, -Math.PI]}
        scale={6.186}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_1_1.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_1_2.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_1_3.geometry}
          material={materials["Material.013"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text007.geometry}
        material={materials["blue_car_light.001"]}
        position={[-97.484, 3.323, 26.443]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={3.751}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text011.geometry}
        material={materials["Material.008"]}
        position={[-106.07, 9.044, 34.929]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={3.801}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube088.geometry}
        material={materials.Material_25}
        position={[-62.408, 19.237, 97.541]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[6.331, 2.326, 12.639]}
      />
      <group
        position={[-36.694, 5.203, 92.438]}
        rotation={[0, -1.561, 0]}
        scale={0.003}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Geisel_MKII_Particle_Board_Geisel_MKII_0_1.geometry}
          material={materials["Chrome_-_Polished_Black_Geisel_MKII"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Geisel_MKII_Particle_Board_Geisel_MKII_0_2.geometry}
          material={materials.Particle_Board_Geisel_MKII}
        />
      </group>
      <group
        position={[-72.013, 24.292, 86.084]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.486, 0.609, 1.369]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1007.geometry}
          material={materials["Walls.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1007_1.geometry}
          material={materials.Walls2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1007_2.geometry}
          material={materials.Windows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1007_3.geometry}
          material={materials.Sidewalk}
        />
      </group>
      <group
        position={[-72.178, -0.415, 69.287]}
        rotation={[0, 0, Math.PI]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5001.geometry}
          material={materials.Mtl_DifferentRow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5001_1.geometry}
          material={materials.Mtl_Concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5001_2.geometry}
          material={materials.Mtl_RoofItems}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5001_3.geometry}
          material={materials.Mtl_Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5001_4.geometry}
          material={materials.Mtl_Ax_Metal}
        />
      </group>
      <group position={[-69.589, 23.617, 94.157]} scale={0.015}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface308_lambert6001_0002_1.geometry}
          material={materials["lambert6.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface308_lambert6001_0002_2.geometry}
          material={materials["09_-_Default.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface308_lambert6001_0002_3.geometry}
          material={materials["Plastic_Black.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface308_lambert6001_0002_4.geometry}
          material={materials["02_-_Default.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface308_lambert6001_0002_5.geometry}
          material={materials["14_-_Default.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface308_lambert6001_0002_6.geometry}
          material={materials["13_-_Default.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface308_lambert6001_0002_7.geometry}
          material={materials.typeBlinn1}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text005.geometry}
        material={materials["Material.016"]}
        position={[-40.49, 9.418, 88.225]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={2.53}
      />
      <group
        position={[-92.347, 3.293, 66.081]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={0.293}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_1.geometry}
          material={materials.Trim_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_2.geometry}
          material={materials.Concrete_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_3.geometry}
          material={materials.Stucco_White_Rims_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_4.geometry}
          material={materials.Roof_A_Rims_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_5.geometry}
          material={materials.Roof_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_6.geometry}
          material={materials.Windows_B}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_7.geometry}
          material={materials.Windows_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_8.geometry}
          material={materials.Details_Electric_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_9.geometry}
          material={materials.Doors_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_10.geometry}
          material={materials.Advertising_Signs_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_11.geometry}
          material={materials.Wall_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_12.geometry}
          material={materials.Gravel_Roof_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_13.geometry}
          material={materials.Wall_B}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_14.geometry}
          material={materials.Wall_Tiles_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_15.geometry}
          material={materials.Wall_C}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_16.geometry}
          material={materials.Pavement_B}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_17.geometry}
          material={materials.Pavement_A}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Trims_Roofs_Trim_A_0001_18.geometry}
          material={materials.Decals_A}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Content-transformed.glb");
