/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HumanCapacity.glb --transform --shadows --keepmaterials --keepmeshes --keepnames 
Files: HumanCapacity.glb [173.42MB] > C:\Users\abhishek\Desktop\dri proj\DRI-Gamified-Final\public\HumanCapacity-transformed.glb [9.68MB] (94%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function HumanCapacity(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/humanCapacity-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Buildings002" position={[-20.405, 22.756, -24.049]}>
          <group
            name="Cube058_Material001_0001"
            position={[-0.743, -21.336, 4.761]}
            rotation={[-Math.PI, 0.088, -Math.PI]}
          >
            <mesh
              name="Cube058_Material001_0001_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube058_Material001_0001_1.geometry}
              material={materials["Material.067"]}
            />
            <mesh
              name="Cube058_Material001_0001_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube058_Material001_0001_2.geometry}
              material={materials["main_planet.001"]}
            />
            <mesh
              name="Cube058_Material001_0001_3"
              castShadow
              receiveShadow
              geometry={nodes.Cube058_Material001_0001_3.geometry}
              material={materials["main_crystal.001"]}
            />
          </group>
          <group
            name="Cube065_Material001_0001"
            position={[-2.337, -18.56, 2.328]}
            rotation={[Math.PI, -0.52, Math.PI]}
          >
            <mesh
              name="Cube065_Material001_0001_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube065_Material001_0001_1.geometry}
              material={materials["Material.067"]}
            />
            <mesh
              name="Cube065_Material001_0001_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube065_Material001_0001_2.geometry}
              material={materials["small_crystal_planet.001"]}
            />
          </group>
          <group
            name="leaves_leaves_0001"
            position={[3.556, -17.682, 7.784]}
            rotation={[-Math.PI, 0.177, -Math.PI]}
          >
            <mesh
              name="leaves_leaves_0001_1"
              castShadow
              receiveShadow
              geometry={nodes.leaves_leaves_0001_1.geometry}
              material={materials["leaves.001"]}
            />
            <mesh
              name="leaves_leaves_0001_2"
              castShadow
              receiveShadow
              geometry={nodes.leaves_leaves_0001_2.geometry}
              material={materials["tree_planet.001"]}
            />
            <mesh
              name="leaves_leaves_0001_3"
              castShadow
              receiveShadow
              geometry={nodes.leaves_leaves_0001_3.geometry}
              material={materials["tree_bark.001"]}
            />
          </group>
          <group
            name="saturn_ring_saturn_0001"
            position={[-1.517, -19.24, 8.628]}
            rotation={[-Math.PI, 0.177, -Math.PI]}
          >
            <mesh
              name="saturn_ring_saturn_0001_1"
              castShadow
              receiveShadow
              geometry={nodes.saturn_ring_saturn_0001_1.geometry}
              material={materials["ring_saturn.001"]}
            />
            <mesh
              name="saturn_ring_saturn_0001_2"
              castShadow
              receiveShadow
              geometry={nodes.saturn_ring_saturn_0001_2.geometry}
              material={materials["saturn.001"]}
            />
          </group>
        </group>
        <group name="ICT_Teachers" position={[-80.867, 28.147, -61.272]}>
          <group
            name="polySurface200_lambert3_0"
            position={[-13.429, -21.122, -8.794]}
            rotation={[0, -0.088, 0]}
          >
            <mesh
              name="polySurface200_lambert3_0_1"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_1.geometry}
              material={materials["lambert6.004"]}
            />
            <mesh
              name="polySurface200_lambert3_0_2"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_2.geometry}
              material={materials["Plastic_Black.003"]}
            />
            <mesh
              name="polySurface200_lambert3_0_3"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_3.geometry}
              material={materials["14_-_Default.003"]}
            />
            <mesh
              name="polySurface200_lambert3_0_4"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_4.geometry}
              material={materials["02_-_Default.004"]}
            />
            <mesh
              name="polySurface200_lambert3_0_5"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_5.geometry}
              material={materials["09_-_Default.004"]}
            />
            <mesh
              name="polySurface200_lambert3_0_6"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_6.geometry}
              material={materials["Tshirt.003"]}
            />
            <mesh
              name="polySurface200_lambert3_0_7"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_7.geometry}
              material={materials["skin_1.003"]}
            />
            <mesh
              name="polySurface200_lambert3_0_8"
              castShadow
              receiveShadow
              geometry={nodes.polySurface200_lambert3_0_8.geometry}
              material={materials["lambert1.001"]}
            />
          </group>
        </group>
        <mesh
          name="Plane020"
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials["Material.005"]}
          position={[-56.455, -0.116, -62.663]}
          scale={[49.2, 50.209, 56.114]}
        />
        <group
          name="Road90_2x2005"
          position={[-72.909, -3.445, -99.164]}
          scale={0.164}
        >
          <mesh
            name="Cube373"
            castShadow
            receiveShadow
            geometry={nodes.Cube373.geometry}
            material={materials["black.007"]}
          />
          <mesh
            name="Cube373_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube373_1.geometry}
            material={materials["Material.017"]}
          />
        </group>
        <mesh
          name="Apartment2_BaseMaterial_0006"
          castShadow
          receiveShadow
          geometry={nodes.Apartment2_BaseMaterial_0006.geometry}
          material={materials["BaseMaterial.002"]}
          position={[-74.274, 2.308, -18.333]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.992}
        />
        <group
          name="bakery006"
          position={[-17.931, 0, -74.858]}
          rotation={[-Math.PI, 0.033, -Math.PI]}
          scale={0.562}
        >
          <mesh
            name="Cube393"
            castShadow
            receiveShadow
            geometry={nodes.Cube393.geometry}
            material={materials["bakery_light.001"]}
          />
          <mesh
            name="Cube393_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube393_1.geometry}
            material={materials["bakery_dark.001"]}
          />
          <mesh
            name="Cube393_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube393_2.geometry}
            material={materials["base.002"]}
          />
          <mesh
            name="Cube393_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube393_3.geometry}
            material={materials["windows .001"]}
          />
        </group>
        <mesh
          name="Bed_2030"
          castShadow
          receiveShadow
          geometry={nodes.Bed_2030.geometry}
          material={materials["World ap.001"]}
          position={[-44.93, -0.069, -36.168]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.01}
        />
        <group
          name="blue_house002"
          position={[-25.415, 0, -74.652]}
          rotation={[-Math.PI, 0.033, -Math.PI]}
          scale={0.562}
        >
          <mesh
            name="Cube394"
            castShadow
            receiveShadow
            geometry={nodes.Cube394.geometry}
            material={materials["blue_house_light.001"]}
          />
          <mesh
            name="Cube394_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube394_1.geometry}
            material={materials["blue_house_dark.001"]}
          />
        </group>
        <group
          name="Building1002"
          position={[-17.199, 0, -33.055]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.465}
        >
          <mesh
            name="Building1"
            castShadow
            receiveShadow
            geometry={nodes.Building1.geometry}
            material={materials["Cover1.001"]}
          />
          <mesh
            name="Building1_1"
            castShadow
            receiveShadow
            geometry={nodes.Building1_1.geometry}
            material={materials.WhiteBuild}
          />
          <mesh
            name="Building1_2"
            castShadow
            receiveShadow
            geometry={nodes.Building1_2.geometry}
            material={materials["Windows.004"]}
          />
          <mesh
            name="Building1_3"
            castShadow
            receiveShadow
            geometry={nodes.Building1_3.geometry}
            material={materials.LightBrownDoor}
          />
          <mesh
            name="Building1_4"
            castShadow
            receiveShadow
            geometry={nodes.Building1_4.geometry}
            material={materials["Edges.003"]}
          />
        </group>
        <group
          name="Building10"
          position={[-14.267, 0, -37.513]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.465}
        >
          <mesh
            name="Building10_1"
            castShadow
            receiveShadow
            geometry={nodes.Building10_1.geometry}
            material={materials.Build1}
          />
          <mesh
            name="Building10_2"
            castShadow
            receiveShadow
            geometry={nodes.Building10_2.geometry}
            material={materials.BrownDoor}
          />
          <mesh
            name="Building10_3"
            castShadow
            receiveShadow
            geometry={nodes.Building10_3.geometry}
            material={materials["Black.001"]}
          />
        </group>
        <group
          name="Building11"
          position={[-72.694, 0, -34.839]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.465}
        >
          <mesh
            name="Building11_1"
            castShadow
            receiveShadow
            geometry={nodes.Building11_1.geometry}
            material={materials["Cover2.003"]}
          />
          <mesh
            name="Building11_2"
            castShadow
            receiveShadow
            geometry={nodes.Building11_2.geometry}
            material={materials["Door1.002"]}
          />
        </group>
        <group
          name="Building2001"
          position={[-64.597, 0, -19.524]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.465}
        >
          <mesh
            name="Building2"
            castShadow
            receiveShadow
            geometry={nodes.Building2.geometry}
            material={materials.Build2}
          />
          <mesh
            name="Building2_1"
            castShadow
            receiveShadow
            geometry={nodes.Building2_1.geometry}
            material={materials.Door2}
          />
        </group>
        <mesh
          name="Building3002"
          castShadow
          receiveShadow
          geometry={nodes.Building3002.geometry}
          material={materials["Cover1.002"]}
          position={[-99.428, 0, -33.229]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.544}
        />
        <group
          name="Building4003"
          position={[-38.153, 0, -29.199]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.465}
        >
          <mesh
            name="Building4"
            castShadow
            receiveShadow
            geometry={nodes.Building4.geometry}
            material={materials.Roof}
          />
          <mesh
            name="Building4_1"
            castShadow
            receiveShadow
            geometry={nodes.Building4_1.geometry}
            material={materials.Cover1}
          />
        </group>
        <mesh
          name="Building5008"
          castShadow
          receiveShadow
          geometry={nodes.Building5008.geometry}
          material={materials["Antena.002"]}
          position={[-23.986, 0, -32.023]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.465}
        />
        <group
          name="Building6002"
          position={[-28.72, 0, -36.083]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.465}
        >
          <mesh
            name="Building6"
            castShadow
            receiveShadow
            geometry={nodes.Building6.geometry}
            material={materials.LightYellow}
          />
          <mesh
            name="Building6_1"
            castShadow
            receiveShadow
            geometry={nodes.Building6_1.geometry}
            material={materials.Building6Top}
          />
        </group>
        <group
          name="Building7"
          position={[-21.168, 0, -86.811]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={0.465}
        >
          <mesh
            name="Building7_1"
            castShadow
            receiveShadow
            geometry={nodes.Building7_1.geometry}
            material={materials.DoorBuilding7}
          />
          <mesh
            name="Building7_2"
            castShadow
            receiveShadow
            geometry={nodes.Building7_2.geometry}
            material={materials.Build6}
          />
        </group>
        <mesh
          name="Building9"
          castShadow
          receiveShadow
          geometry={nodes.Building9.geometry}
          material={materials.Build7}
          position={[-18.52, 0, -36.458]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.465}
        />
        <group
          name="FireStation"
          position={[-40.095, 0, -19.318]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.465}
        >
          <mesh
            name="FireStation_1"
            castShadow
            receiveShadow
            geometry={nodes.FireStation_1.geometry}
            material={materials.FireStation}
          />
          <mesh
            name="FireStation_2"
            castShadow
            receiveShadow
            geometry={nodes.FireStation_2.geometry}
            material={materials.FireStation2}
          />
          <mesh
            name="FireStation_3"
            castShadow
            receiveShadow
            geometry={nodes.FireStation_3.geometry}
            material={materials.PoliceStationRoof}
          />
        </group>
        <group
          name="fonana_multi_0003"
          position={[-69.605, 0, -31.801]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.356}
        >
          <mesh
            name="fonana_multi_0"
            castShadow
            receiveShadow
            geometry={nodes.fonana_multi_0.geometry}
            material={materials.multi}
          />
          <mesh
            name="fonana_multi_0_1"
            castShadow
            receiveShadow
            geometry={nodes.fonana_multi_0_1.geometry}
            material={materials["acqua.001"]}
          />
        </group>
        <group
          name="gas_station001"
          position={[-13.012, 0, -55.356]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.504}
        >
          <mesh
            name="Cube395"
            castShadow
            receiveShadow
            geometry={nodes.Cube395.geometry}
            material={materials["black.008"]}
          />
          <mesh
            name="Cube395_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube395_1.geometry}
            material={materials["gray_street.002"]}
          />
          <mesh
            name="Cube395_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube395_2.geometry}
            material={materials["gas_light.001"]}
          />
          <mesh
            name="Cube395_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube395_3.geometry}
            material={materials["gas_dark.001"]}
          />
          <mesh
            name="Cube395_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube395_4.geometry}
            material={materials["gas_neon.001"]}
          />
        </group>
        <mesh
          name="grass001"
          castShadow
          receiveShadow
          geometry={nodes.grass001.geometry}
          material={materials["posters.001"]}
          position={[-64.664, 0, -22.233]}
          scale={[0.574, 1, 0.637]}
        />
        <group
          name="Hospital"
          position={[-50.307, 0, -29.181]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.465}
        >
          <mesh
            name="Hospital_1"
            castShadow
            receiveShadow
            geometry={nodes.Hospital_1.geometry}
            material={materials.Cross}
          />
          <mesh
            name="Hospital_2"
            castShadow
            receiveShadow
            geometry={nodes.Hospital_2.geometry}
            material={materials.Hospital2}
          />
        </group>
        <group
          name="House1"
          position={[-98.234, 0, -20.213]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.675}
        >
          <mesh
            name="House1_1"
            castShadow
            receiveShadow
            geometry={nodes.House1_1.geometry}
            material={materials.House}
          />
          <mesh
            name="House1_2"
            castShadow
            receiveShadow
            geometry={nodes.House1_2.geometry}
            material={materials.HouseRoof}
          />
          <mesh
            name="House1_3"
            castShadow
            receiveShadow
            geometry={nodes.House1_3.geometry}
            material={materials.HouseEdges}
          />
          <mesh
            name="House1_4"
            castShadow
            receiveShadow
            geometry={nodes.House1_4.geometry}
            material={materials.HouseBlack}
          />
        </group>
        <group
          name="House2"
          position={[-81.042, 0, -24.404]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.675}
        >
          <mesh
            name="House2_1"
            castShadow
            receiveShadow
            geometry={nodes.House2_1.geometry}
            material={materials.HouseRoof2}
          />
          <mesh
            name="House2_2"
            castShadow
            receiveShadow
            geometry={nodes.House2_2.geometry}
            material={materials.DoorHouse2}
          />
          <mesh
            name="House2_3"
            castShadow
            receiveShadow
            geometry={nodes.House2_3.geometry}
            material={materials.HouseEdges2}
          />
        </group>
        <group
          name="House3"
          position={[-95.946, 0, -24.172]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.675}
        >
          <mesh
            name="House3_1"
            castShadow
            receiveShadow
            geometry={nodes.House3_1.geometry}
            material={materials.House3}
          />
          <mesh
            name="House3_2"
            castShadow
            receiveShadow
            geometry={nodes.House3_2.geometry}
            material={materials.HouseRoof3}
          />
          <mesh
            name="House3_3"
            castShadow
            receiveShadow
            geometry={nodes.House3_3.geometry}
            material={materials.HouseEdges3}
          />
        </group>
        <group
          name="House4"
          position={[-88.536, 0, -24.362]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.675}
        >
          <mesh
            name="House4_1"
            castShadow
            receiveShadow
            geometry={nodes.House4_1.geometry}
            material={materials.House4}
          />
          <mesh
            name="House4_2"
            castShadow
            receiveShadow
            geometry={nodes.House4_2.geometry}
            material={materials.HouseRoof4}
          />
          <mesh
            name="House4_3"
            castShadow
            receiveShadow
            geometry={nodes.House4_3.geometry}
            material={materials.HouseEdges4}
          />
        </group>
        <group
          name="market001"
          position={[-12.595, 0, -71.688]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.605}
        >
          <mesh
            name="Cube398"
            castShadow
            receiveShadow
            geometry={nodes.Cube398.geometry}
            material={materials["sport_car_light.001"]}
          />
          <mesh
            name="Cube398_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube398_1.geometry}
            material={materials["sport_car_dark.001"]}
          />
        </group>
        <mesh
          name="Object_10001"
          castShadow
          receiveShadow
          geometry={nodes.Object_10001.geometry}
          material={materials["Material.037"]}
          position={[-23.245, 0, -105.235]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.658}
        />
        <mesh
          name="Object_21001"
          castShadow
          receiveShadow
          geometry={nodes.Object_21001.geometry}
          material={materials["Material.038"]}
          position={[-23.245, 0, -105.235]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.658}
        />
        <group
          name="Object_35"
          position={[-23.91, 0, -103.773]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.658}
        >
          <mesh
            name="Object_33001"
            castShadow
            receiveShadow
            geometry={nodes.Object_33001.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            name="Object_33001_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_33001_1.geometry}
            material={materials["Material.039"]}
          />
          <mesh
            name="Object_33001_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_33001_2.geometry}
            material={materials.Smeared_Wall}
          />
          <mesh
            name="Object_33001_3"
            castShadow
            receiveShadow
            geometry={nodes.Object_33001_3.geometry}
            material={materials["Material.040"]}
          />
          <mesh
            name="Object_33001_4"
            castShadow
            receiveShadow
            geometry={nodes.Object_33001_4.geometry}
            material={materials.CLANTA}
          />
          <mesh
            name="Object_33001_5"
            castShadow
            receiveShadow
            geometry={nodes.Object_33001_5.geometry}
            material={materials.USA0}
          />
          <mesh
            name="Object_33001_6"
            castShadow
            receiveShadow
            geometry={nodes.Object_33001_6.geometry}
            material={materials["Material.041"]}
          />
        </group>
        <group
          name="pizzeria005"
          position={[-13.269, 0, -60.992]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.6}
        >
          <mesh
            name="Cube399"
            castShadow
            receiveShadow
            geometry={nodes.Cube399.geometry}
            material={materials["pizzeria_light.001"]}
          />
          <mesh
            name="Cube399_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube399_1.geometry}
            material={materials["pizzeria_dark.001"]}
          />
        </group>
        <group
          name="Root023"
          position={[-12.243, 0.18, -47.727]}
          rotation={[Math.PI, -1.562, Math.PI]}
          scale={0.074}
        >
          <mesh
            name="Root046"
            castShadow
            receiveShadow
            geometry={nodes.Root046.geometry}
            material={materials["Buildings City_mat_0_0_1.004"]}
          />
          <mesh
            name="Root046_1"
            castShadow
            receiveShadow
            geometry={nodes.Root046_1.geometry}
            material={materials["Buildings City_mat_1_1_1.008"]}
          />
          <mesh
            name="Root046_2"
            castShadow
            receiveShadow
            geometry={nodes.Root046_2.geometry}
            material={materials["Buildings City_mat_2_2_1.006"]}
          />
          <mesh
            name="Root046_3"
            castShadow
            receiveShadow
            geometry={nodes.Root046_3.geometry}
            material={materials["Buildings City_mat_3_3_1.004"]}
          />
        </group>
        <group
          name="School"
          position={[-86.731, 0, -35.024]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.535}
        >
          <mesh
            name="School_1"
            castShadow
            receiveShadow
            geometry={nodes.School_1.geometry}
            material={materials.SchoolRoof}
          />
          <mesh
            name="School_2"
            castShadow
            receiveShadow
            geometry={nodes.School_2.geometry}
            material={materials.Clock}
          />
        </group>
        <mesh
          name="small_rocks_small_rocks_0001"
          castShadow
          receiveShadow
          geometry={nodes.small_rocks_small_rocks_0001.geometry}
          material={materials["small_rocks.001"]}
          position={[-21.142, 1.662, -19.37]}
          rotation={[-Math.PI, 0.088, -Math.PI]}
        />
        <mesh
          name="Text002"
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials["Material.065"]}
          position={[-23.36, 3.998, -103.79]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={3.124}
        />
        <group
          name="tree_1004"
          position={[-16.276, -0.184, -77.65]}
          scale={0.875}
        >
          <mesh
            name="Sphere003"
            castShadow
            receiveShadow
            geometry={nodes.Sphere003.geometry}
            material={materials["green_house_light.001"]}
          />
          <mesh
            name="Sphere003_1"
            castShadow
            receiveShadow
            geometry={nodes.Sphere003_1.geometry}
            material={materials["green_house_dark.001"]}
          />
          <mesh
            name="Sphere003_2"
            castShadow
            receiveShadow
            geometry={nodes.Sphere003_2.geometry}
            material={materials["g_light_off.001"]}
          />
        </group>
        <mesh
          name="Window005"
          castShadow
          receiveShadow
          geometry={nodes.Window005.geometry}
          material={materials["Buildings City_mat_3_3_1.005"]}
          position={[-22.125, 0.876, -66.72]}
          rotation={[0, -1.568, 0]}
          scale={0.091}
        />
        <group
          name="Banc_1"
          position={[-48.992, 0.454, -87.601]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[0.017, 0.017, 0.133]}
        >
          <mesh
            name="Banc_1_1"
            castShadow
            receiveShadow
            geometry={nodes.Banc_1_1.geometry}
            material={materials.Couleur_Planches}
          />
          <mesh
            name="Banc_1_2"
            castShadow
            receiveShadow
            geometry={nodes.Banc_1_2.geometry}
            material={materials.Couleur_Barres}
          />
        </group>
        <mesh
          name="Car_08_2001"
          castShadow
          receiveShadow
          geometry={nodes.Car_08_2001.geometry}
          material={materials["World ap.003"]}
          position={[-75.619, 0.133, -92.53]}
          rotation={[Math.PI, -0.041, 0]}
          scale={0.015}
        />
        <mesh
          name="Cube087"
          castShadow
          receiveShadow
          geometry={nodes.Cube087.geometry}
          material={nodes.Cube087.material}
          position={[-35.24, 0.525, -116.06]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[3.763, 0.75, 0.216]}
        />
        <group
          name="Cube100"
          position={[-58.385, 0.001, -94.003]}
          scale={[8.244, 0.086, 1.746]}
        >
          <mesh
            name="Cube404"
            castShadow
            receiveShadow
            geometry={nodes.Cube404.geometry}
            material={materials["Material.062"]}
          />
          <mesh
            name="Cube404_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube404_1.geometry}
            material={materials["Material.063"]}
          />
        </group>
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.058"]}
          position={[-57.979, -0.058, -90.336]}
          scale={[1.458, 0.069, 1.916]}
        />
        <group
          name="Cylinder045"
          position={[-41.844, 21.612, -93.701]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[2.564, 0.64, 2.564]}
        >
          <mesh
            name="Cylinder060"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder060.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cylinder060_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder060_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Cylinder044"
          position={[-52.407, 21.612, -60.585]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[2.564, 0.64, 2.564]}
        >
          <mesh
            name="Cylinder054"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder054.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Cylinder054_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder054_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Cylinder051"
          position={[-41.844, 21.612, -93.701]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[2.564, 0.64, 2.564]}
        >
          <mesh
            name="Cylinder045_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_1.geometry}
            material={materials.border}
          />
          <mesh
            name="Cylinder045_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_2.geometry}
            material={materials.material}
          />
          <mesh
            name="Cylinder045_3"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_3.geometry}
            material={materials.typeBlinn}
          />
          <mesh
            name="Cylinder045_4"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_4.geometry}
            material={materials["Material.065"]}
          />
          <mesh
            name="Cylinder045_5"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_5.geometry}
            material={materials.skin_1}
          />
          <mesh
            name="Cylinder045_6"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_6.geometry}
            material={materials["lambert3.002"]}
          />
          <mesh
            name="Cylinder045_7"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_7.geometry}
            material={materials.Tshirt}
          />
          <mesh
            name="Cylinder045_8"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder045_8.geometry}
            material={materials.Sticck}
          />
        </group>
        <group name="hotel004" position={[-52.39, 0, -111.113]} scale={0.572}>
          <mesh
            name="Cube397"
            castShadow
            receiveShadow
            geometry={nodes.Cube397.geometry}
            material={materials["hotel_light.001"]}
          />
          <mesh
            name="Cube397_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube397_1.geometry}
            material={materials["hotel_dark.001"]}
          />
        </group>
        <group
          name="Monumentum"
          position={[-67.438, 0, -94.011]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.12}
        >
          <mesh
            name="Monumentum_1"
            castShadow
            receiveShadow
            geometry={nodes.Monumentum_1.geometry}
            material={materials.Grass}
          />
          <mesh
            name="Monumentum_2"
            castShadow
            receiveShadow
            geometry={nodes.Monumentum_2.geometry}
            material={materials.Monumentum}
          />
        </group>
        <mesh
          name="Object_2"
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.School}
          position={[-38.954, 0.237, -93.976]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={2.262}
        />
        <group
          name="PoliceStation"
          position={[-53.811, 0, -103.678]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.696}
        >
          <mesh
            name="PoliceStation_1"
            castShadow
            receiveShadow
            geometry={nodes.PoliceStation_1.geometry}
            material={materials.PoliceStation}
          />
          <mesh
            name="PoliceStation_2"
            castShadow
            receiveShadow
            geometry={nodes.PoliceStation_2.geometry}
            material={materials.PoliceStation2}
          />
        </group>
        <group
          name="polySurface2_typeBlinn_0"
          position={[-46.679, 3.068, -92.92]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.016}
        >
          <mesh
            name="polySurface2_typeBlinn_0001"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001.geometry}
            material={materials["Material.036"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_1"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_1.geometry}
            material={materials["lambert3.002"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_2"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_2.geometry}
            material={materials["Material.065"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_3"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_3.geometry}
            material={materials["02_-_Default.004"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_4"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_4.geometry}
            material={materials["09_-_Default.003"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_5"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_5.geometry}
            material={materials["PILLARS.002"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_6"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_6.geometry}
            material={materials["Main.002"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_7"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_7.geometry}
            material={materials["black.009"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_8"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_8.geometry}
            material={materials["Plastic_Black.003"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_9"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_9.geometry}
            material={materials["lambert6.004"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_10"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_10.geometry}
            material={materials["14_-_Default.003"]}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_11"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_11.geometry}
            material={materials.skin_1}
          />
          <mesh
            name="polySurface2_typeBlinn_0001_12"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_typeBlinn_0001_12.geometry}
            material={materials.Tshirt}
          />
        </group>
        <group
          name="Soccer_Field_1"
          position={[-42.33, 0.026, -111.74]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.608, 0.913, 0.259]}
        >
          <mesh
            name="Soccer_Field_1_1"
            castShadow
            receiveShadow
            geometry={nodes.Soccer_Field_1_1.geometry}
            material={materials.Green}
          />
          <mesh
            name="Soccer_Field_1_2"
            castShadow
            receiveShadow
            geometry={nodes.Soccer_Field_1_2.geometry}
            material={materials["Material.038"]}
          />
          <mesh
            name="Soccer_Field_1_3"
            castShadow
            receiveShadow
            geometry={nodes.Soccer_Field_1_3.geometry}
            material={materials["material.002"]}
          />
          <mesh
            name="Soccer_Field_1_4"
            castShadow
            receiveShadow
            geometry={nodes.Soccer_Field_1_4.geometry}
            material={materials.Black_metal}
          />
          <mesh
            name="Soccer_Field_1_5"
            castShadow
            receiveShadow
            geometry={nodes.Soccer_Field_1_5.geometry}
            material={materials.Metal}
          />
        </group>
        <mesh
          name="Text012"
          castShadow
          receiveShadow
          geometry={nodes.Text012.geometry}
          material={materials["Material.002"]}
          position={[-39.747, 11.232, -106.502]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={2.733}
        />
        <mesh
          name="tree_2001"
          castShadow
          receiveShadow
          geometry={nodes.tree_2001.geometry}
          material={materials["G_light_off.001"]}
          position={[-56.516, -0.144, -112.267]}
          rotation={[0, Math.PI / 9, 0]}
          scale={0.625}
        />
        <group
          name="Curve_typeBlinn001_0"
          position={[-52.592, 4.013, -60.936]}
          rotation={[0, -1.533, 0]}
          scale={[71.707, 71.707, 23.345]}
        >
          <mesh
            name="Curve_typeBlinn001_0001"
            castShadow
            receiveShadow
            geometry={nodes.Curve_typeBlinn001_0001.geometry}
            material={materials["typeBlinn.004"]}
          />
          <mesh
            name="Curve_typeBlinn001_0001_1"
            castShadow
            receiveShadow
            geometry={nodes.Curve_typeBlinn001_0001_1.geometry}
            material={materials["black.010"]}
          />
          <mesh
            name="Curve_typeBlinn001_0001_2"
            castShadow
            receiveShadow
            geometry={nodes.Curve_typeBlinn001_0001_2.geometry}
            material={materials["PILLARS.003"]}
          />
          <mesh
            name="Curve_typeBlinn001_0001_3"
            castShadow
            receiveShadow
            geometry={nodes.Curve_typeBlinn001_0001_3.geometry}
            material={materials["lambert6.004"]}
          />
        </group>
        <mesh
          name="Cylinder050"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050.geometry}
          material={materials.typeBlinn}
          position={[-52.407, 21.612, -60.585]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[2.564, 0.64, 2.564]}
        />
        <group
          name="Object_43"
          position={[-52.367, -3.001, -59.98]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[6.1, 6.1, 9.202]}
        >
          <mesh
            name="Object_41001"
            castShadow
            receiveShadow
            geometry={nodes.Object_41001.geometry}
            material={materials.Leaves}
          />
          <mesh
            name="Object_41001_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_41001_1.geometry}
            material={materials.Quartz_Stairs}
          />
          <mesh
            name="Object_41001_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_41001_2.geometry}
            material={materials.Glowstone}
          />
          <mesh
            name="Object_41001_3"
            castShadow
            receiveShadow
            geometry={nodes.Object_41001_3.geometry}
            material={materials.Wooden_Slab}
          />
          <mesh
            name="Object_41001_4"
            castShadow
            receiveShadow
            geometry={nodes.Object_41001_4.geometry}
            material={materials.Block_of_Quartz}
          />
          <mesh
            name="Object_41001_5"
            castShadow
            receiveShadow
            geometry={nodes.Object_41001_5.geometry}
            material={materials.Stationary_Water}
          />
          <mesh
            name="Object_41001_6"
            castShadow
            receiveShadow
            geometry={nodes.Object_41001_6.geometry}
            material={materials.Ladder}
          />
        </group>
        <mesh
          name="Object_3"
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["Scene_-_Root.001"]}
          position={[-93.892, 0, -69.364]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.019}
        />
        <group
          name="Object_50"
          position={[-79.908, 0.056, -55.294]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.376, 0.229, 0.302]}
        >
          <mesh
            name="Object_33"
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials["GREY.003"]}
          />
          <mesh
            name="Object_33_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_33_1.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            name="Object_33_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_33_2.geometry}
            material={materials.CopperTrim}
          />
          <mesh
            name="Object_33_3"
            castShadow
            receiveShadow
            geometry={nodes.Object_33_3.geometry}
            material={materials["Roof.002"]}
          />
          <mesh
            name="Object_33_4"
            castShadow
            receiveShadow
            geometry={nodes.Object_33_4.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            name="Object_33_5"
            castShadow
            receiveShadow
            geometry={nodes.Object_33_5.geometry}
            material={materials.material_0}
          />
        </group>
        <group
          name="polySurface2_lambert6_0001"
          position={[-80.029, 15.701, -55.438]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.022}
        >
          <mesh
            name="polySurface2_lambert6_0001_1"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_lambert6_0001_1.geometry}
            material={materials.Sticck}
          />
          <mesh
            name="polySurface2_lambert6_0001_2"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_lambert6_0001_2.geometry}
            material={materials["01_-_Default.002"]}
          />
        </group>
        <group
          name="polySurface2_lambert6_0002"
          position={[-80.029, 15.701, -55.438]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.022}
        >
          <mesh
            name="polySurface2_lambert6_0002_1"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_lambert6_0002_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="polySurface2_lambert6_0002_2"
            castShadow
            receiveShadow
            geometry={nodes.polySurface2_lambert6_0002_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/humanCapacity-transformed.glb");
