/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Infrastructure.glb --transform --shadows --keepmaterials --keepmeshes --keepnames 
Files: Infrastructure.glb [41.64MB] > C:\Users\abhishek\Desktop\dri proj\DRI-Gamified-Final\public\Infrastructure-transformed.glb [3.87MB] (91%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Infrastructure(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/infrastructure-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Electricity" position={[98.355, 28.499, -33.166]}>
          <mesh
            name="pole_Mat_0003"
            castShadow
            receiveShadow
            geometry={nodes.pole_Mat_0003.geometry}
            material={materials["material.005"]}
            position={[-8.322, -15.422, 16.624]}
            rotation={[0, 0, 0.088]}
          />
        </group>
        <group
          name="Plane019"
          position={[62.906, -0.224, -56.25]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[49.2, 50.209, 56.114]}
        >
          <mesh
            name="Plane006"
            castShadow
            receiveShadow
            geometry={nodes.Plane006.geometry}
            material={materials["Material.054"]}
          />
          <mesh
            name="Plane006_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane006_1.geometry}
            material={materials["Pebbles.001"]}
          />
        </group>
        <group
          name="Road90_2x2"
          position={[99.187, -3.115, -72.892]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.164}
        >
          <mesh
            name="Cube257"
            castShadow
            receiveShadow
            geometry={nodes.Cube257.geometry}
            material={materials["black.005"]}
          />
          <mesh
            name="Cube257_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube257_1.geometry}
            material={materials["Material.043"]}
          />
        </group>
        <mesh
          name="Apartment1_BaseMaterial_0002"
          castShadow
          receiveShadow
          geometry={nodes.Apartment1_BaseMaterial_0002.geometry}
          material={materials["BaseMaterial.003"]}
          position={[20.011, 2.631, -76.043]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group
          name="bakery002"
          position={[42.807, 0.149, -49.093]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Cube234"
            castShadow
            receiveShadow
            geometry={nodes.Cube234.geometry}
            material={materials["bakery_light.002"]}
          />
          <mesh
            name="Cube234_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube234_1.geometry}
            material={materials["bakery_dark.002"]}
          />
          <mesh
            name="Cube234_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube234_2.geometry}
            material={materials["base.003"]}
          />
          <mesh
            name="Cube234_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube234_3.geometry}
            material={materials["windows .002"]}
          />
        </group>
        <group
          name="blue_house004"
          position={[68.529, 0, -69.756]}
          scale={0.602}
        >
          <mesh
            name="Cube238"
            castShadow
            receiveShadow
            geometry={nodes.Cube238.geometry}
            material={materials["blue_house_light.002"]}
          />
          <mesh
            name="Cube238_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube238_1.geometry}
            material={materials["blue_house_dark.002"]}
          />
        </group>
        <group
          name="cinema002"
          position={[28.097, -0.138, -74.753]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Cube235"
            castShadow
            receiveShadow
            geometry={nodes.Cube235.geometry}
            material={materials["cinema_light.002"]}
          />
          <mesh
            name="Cube235_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube235_1.geometry}
            material={materials["cinema_dark.002"]}
          />
          <mesh
            name="Cube235_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube235_2.geometry}
            material={materials["black.004"]}
          />
          <mesh
            name="Cube235_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube235_3.geometry}
            material={materials["light.002"]}
          />
          <mesh
            name="Cube235_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube235_4.geometry}
            material={materials["posters.002"]}
          />
        </group>
        <group
          name="coffe_shop002"
          position={[75.473, -0.238, -57.4]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Text012"
            castShadow
            receiveShadow
            geometry={nodes.Text012.geometry}
            material={materials["coffe_shop_light.002"]}
          />
          <mesh
            name="Text012_1"
            castShadow
            receiveShadow
            geometry={nodes.Text012_1.geometry}
            material={materials["coffe_shop_dark.002"]}
          />
        </group>
        <mesh
          name="Cube002_Material_0006"
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Material_0006.geometry}
          material={materials["Material.053"]}
          position={[42.126, -0.024, -73.608]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={0.352}
        />
        <mesh
          name="Cube178"
          castShadow
          receiveShadow
          geometry={nodes.Cube178.geometry}
          material={nodes.Cube178.material}
          position={[41.183, -0.345, -72.91]}
          scale={[4.774, 0.237, 4.616]}
        />
        <group
          name="Cylinder001_Material001_0018"
          position={[43.152, 0.493, -75.552]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
          scale={[0.437, 0.437, 0.678]}
        >
          <mesh
            name="Cylinder001_Material001_0018_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material001_0018_1.geometry}
            material={materials["Material.047"]}
          />
          <mesh
            name="Cylinder001_Material001_0018_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material001_0018_2.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cylinder001_Material001_0018_3"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material001_0018_3.geometry}
            material={materials["Material.049"]}
          />
          <mesh
            name="Cylinder001_Material001_0018_4"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material001_0018_4.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cylinder001_Material001_0018_5"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material001_0018_5.geometry}
            material={materials["Material.051"]}
          />
          <mesh
            name="Cylinder001_Material001_0018_6"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material001_0018_6.geometry}
            material={materials["Material.052"]}
          />
        </group>
        <group
          name="dom_byta_cover004_dom_byta_4kk_0001"
          position={[63.304, 0, -63.699]}
          scale={0.341}
        >
          <mesh
            name="dom_byta_cover004_dom_byta_4kk_0001_1"
            castShadow
            receiveShadow
            geometry={nodes.dom_byta_cover004_dom_byta_4kk_0001_1.geometry}
            material={materials["dom_byta_4kk.002"]}
          />
          <mesh
            name="dom_byta_cover004_dom_byta_4kk_0001_2"
            castShadow
            receiveShadow
            geometry={nodes.dom_byta_cover004_dom_byta_4kk_0001_2.geometry}
            material={materials["ograda.002"]}
          />
          <mesh
            name="dom_byta_cover004_dom_byta_4kk_0001_3"
            castShadow
            receiveShadow
            geometry={nodes.dom_byta_cover004_dom_byta_4kk_0001_3.geometry}
            material={materials["side_1_15.002"]}
          />
          <mesh
            name="dom_byta_cover004_dom_byta_4kk_0001_4"
            castShadow
            receiveShadow
            geometry={nodes.dom_byta_cover004_dom_byta_4kk_0001_4.geometry}
            material={materials["side_2_6.002"]}
          />
        </group>
        <group
          name="green_house003"
          position={[69.834, 0, -43.404]}
          scale={0.638}
        >
          <mesh
            name="Cube255"
            castShadow
            receiveShadow
            geometry={nodes.Cube255.geometry}
            material={materials["green_house_light.002"]}
          />
          <mesh
            name="Cube255_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube255_1.geometry}
            material={materials["green_house_dark.002"]}
          />
        </group>
        <group
          name="hotel002"
          position={[29.643, -0.238, -62.119]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Cube236"
            castShadow
            receiveShadow
            geometry={nodes.Cube236.geometry}
            material={materials["hotel_light.002"]}
          />
          <mesh
            name="Cube236_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube236_1.geometry}
            material={materials["hotel_dark.002"]}
          />
        </group>
        <mesh
          name="House001"
          castShadow
          receiveShadow
          geometry={nodes.House001.geometry}
          material={materials["World ap.002"]}
          position={[49.935, 1.96, -44.491]}
          rotation={[0, 0, Math.PI]}
          scale={0.01}
        />
        <group
          name="Lowpoly_Tree_07_Material_0026"
          position={[22.807, 2.003, -76.988]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Lowpoly_Tree_07_Material_0002"
            castShadow
            receiveShadow
            geometry={nodes.Lowpoly_Tree_07_Material_0002.geometry}
            material={materials["Material.045"]}
          />
          <mesh
            name="Lowpoly_Tree_07_Material_0002_1"
            castShadow
            receiveShadow
            geometry={nodes.Lowpoly_Tree_07_Material_0002_1.geometry}
            material={materials["Material.046"]}
          />
        </group>
        <mesh
          name="Object_17007"
          castShadow
          receiveShadow
          geometry={nodes.Object_17007.geometry}
          material={materials["roof.003"]}
          position={[39.196, -0.234, -74.57]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={2.139}
        />
        <mesh
          name="Object_4008"
          castShadow
          receiveShadow
          geometry={nodes.Object_4008.geometry}
          material={materials["Radio.002"]}
          position={[61.461, 0, -68.498]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.756}
        />
        <group
          name="pCube2_phong5_0036"
          position={[43.244, -0.19, -77.472]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[4.282, 0.078, 0.085]}
        >
          <mesh
            name="pCube2_phong5_0036_1"
            castShadow
            receiveShadow
            geometry={nodes.pCube2_phong5_0036_1.geometry}
            material={materials["phong5.002"]}
          />
          <mesh
            name="pCube2_phong5_0036_2"
            castShadow
            receiveShadow
            geometry={nodes.pCube2_phong5_0036_2.geometry}
            material={materials["phong6.002"]}
          />
        </group>
        <group
          name="pizzeria002"
          position={[37.452, 0.154, -47.576]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <mesh
            name="Cube237"
            castShadow
            receiveShadow
            geometry={nodes.Cube237.geometry}
            material={materials["pizzeria_light.002"]}
          />
          <mesh
            name="Cube237_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube237_1.geometry}
            material={materials["pizzeria_dark.002"]}
          />
        </group>
        <mesh
          name="SP_TNR_Electricpole_1_SP_TNR_Electricpole_1-8_0002"
          castShadow
          receiveShadow
          geometry={
            nodes["SP_TNR_Electricpole_1_SP_TNR_Electricpole_1-8_0002"].geometry
          }
          material={materials["SP_TNR_Electricpole_1-8_0.002"]}
          position={[71.626, -0.005, -56.162]}
          rotation={[0, Math.PI / 2, 0]}
          scale={2.886}
        />
        <group
          name="yellow_house003"
          position={[71.831, 0, -37.538]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.638}
        >
          <mesh
            name="Cube256"
            castShadow
            receiveShadow
            geometry={nodes.Cube256.geometry}
            material={materials["yellow_house_light.002"]}
          />
          <mesh
            name="Cube256_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube256_1.geometry}
            material={materials["yellow_house_dark.002"]}
          />
        </group>
        <mesh
          name="Cube177"
          castShadow
          receiveShadow
          geometry={nodes.Cube177.geometry}
          material={materials["Walls.003"]}
          position={[116.848, 0.565, -35.688]}
          scale={[3.763, 0.75, 0.216]}
        />
        <group
          name="Cylinder003"
          position={[98.274, 26.097, -58.511]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.564, 0.64, 2.564]}
        >
          <mesh
            name="Cylinder049_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder049_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="Cylinder049_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder049_2.geometry}
            material={materials["Material.056"]}
          />
        </group>
        <mesh
          name="Cylinder049"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder049.geometry}
          material={materials.lambert6}
          position={[98.274, 26.097, -58.511]}
          rotation={[-Math.PI / 2, 0, Math.PI]}
          scale={[2.564, 0.64, 2.564]}
        />
        <mesh
          name="Cylinder_Environment1_0001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_Environment1_0001.geometry}
          material={materials["Environment.005"]}
          position={[98.645, 1.089, -73.496]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <group
          name="Material2001"
          position={[82.173, -0.222, -22.64]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.005}
        >
          <mesh
            name="Material2001_1"
            castShadow
            receiveShadow
            geometry={nodes.Material2001_1.geometry}
            material={materials["HWWT_Metal-Stucco.002"]}
          />
          <mesh
            name="Material2001_2"
            castShadow
            receiveShadow
            geometry={nodes.Material2001_2.geometry}
            material={materials["material.006"]}
          />
        </group>
        <group
          name="Object_4005"
          position={[58.625, 1.438, -19.329]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            name="Object_2009"
            castShadow
            receiveShadow
            geometry={nodes.Object_2009.geometry}
            material={materials["Default_Material.002"]}
          />
          <mesh
            name="Object_2009_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_2009_1.geometry}
            material={materials["Color_003.002"]}
          />
          <mesh
            name="Object_2009_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_2009_2.geometry}
            material={materials["Translucent_Glass_Safety.002"]}
          />
          <mesh
            name="Object_2009_3"
            castShadow
            receiveShadow
            geometry={nodes.Object_2009_3.geometry}
            material={materials["Wood__Floor.002"]}
          />
        </group>
        <mesh
          name="pole_Mat_0002"
          castShadow
          receiveShadow
          geometry={nodes.pole_Mat_0002.geometry}
          material={materials["material.005"]}
          position={[90.027, 0, -14.943]}
          rotation={[-Math.PI, 0, -Math.PI / 2]}
          scale={0.001}
        />
        <mesh
          name="Text008"
          castShadow
          receiveShadow
          geometry={nodes.Text008.geometry}
          material={materials["Material.014"]}
          position={[108.699, 10.389, -58.498]}
          rotation={[Math.PI / 2, 0, -Math.PI]}
          scale={3.801}
        />
        <mesh
          name="acqua002"
          castShadow
          receiveShadow
          geometry={nodes.acqua002.geometry}
          material={materials["acqua.002"]}
          position={[27.691, 0.432, -92.697]}
          scale={0.31}
        />
        <mesh
          name="Building5013"
          castShadow
          receiveShadow
          geometry={nodes.Building5013.geometry}
          material={materials["Material.044"]}
          position={[56.368, 9.336, -99.332]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.803}
        />
        <group
          name="pCylinder31_Head_human003_0001"
          position={[70.423, 22.551, -87.843]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.167}
        >
          <mesh
            name="pCylinder31_Head_human003_0001_1"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder31_Head_human003_0001_1.geometry}
            material={materials["Head_human.003"]}
          />
          <mesh
            name="pCylinder31_Head_human003_0001_2"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder31_Head_human003_0001_2.geometry}
            material={materials["body_human.003"]}
          />
          <mesh
            name="pCylinder31_Head_human003_0001_3"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder31_Head_human003_0001_3.geometry}
            material={materials["GLOBE_BLACK.003"]}
          />
        </group>
        <group
          name="pCylinder31_Head_human003_0002"
          position={[70.423, 22.551, -87.843]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.167}
        >
          <mesh
            name="pCylinder31_Head_human003_0002_1"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder31_Head_human003_0002_1.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            name="pCylinder31_Head_human003_0002_2"
            castShadow
            receiveShadow
            geometry={nodes.pCylinder31_Head_human003_0002_2.geometry}
            material={materials["Material.056"]}
          />
        </group>
        <group
          name="Root047"
          position={[70.429, 0.208, -88.938]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.249, 0.249, 0.249]}
        >
          <mesh
            name="Root045"
            castShadow
            receiveShadow
            geometry={nodes.Root045.geometry}
            material={materials["Buildings City_mat_0_0_1.007"]}
          />
          <mesh
            name="Root045_1"
            castShadow
            receiveShadow
            geometry={nodes.Root045_1.geometry}
            material={materials["Buildings City_mat_1_1_1.011"]}
          />
          <mesh
            name="Root045_2"
            castShadow
            receiveShadow
            geometry={nodes.Root045_2.geometry}
            material={materials["Buildings City_mat_2_2_1.009"]}
          />
          <mesh
            name="Root045_3"
            castShadow
            receiveShadow
            geometry={nodes.Root045_3.geometry}
            material={materials["Buildings City_mat_3_3_1.007"]}
          />
        </group>
        <mesh
          name="Window011"
          castShadow
          receiveShadow
          geometry={nodes.Window011.geometry}
          material={materials["Buildings City_mat_3_3_1.006"]}
          position={[54.594, 1.948, -88.286]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.208}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/infrastructure-transformed.glb')
