/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PlayBtn(props) {
  const { nodes, materials } = useGLTF("/PLAY_BUTTON.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={[1, 0.071, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.004"]}
        position={[0.076, 0, 0]}
        scale={0.46}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.004"]}
        position={[-0.083, -0.163, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.46}
      />
    </group>
  );
}

useGLTF.preload("/PLAY_BUTTON.glb");
